apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name:openapi-petstore}-sidecar-config
  namespace: ${namespace:openapi-petstore}
  labels:
    app.kubernetes.io/name: ${name:openapi-petstore}
    app.kubernetes.io/component: sidecar
    app.kubernetes.io/part-of: lightapi
data:
  startup.yml: |
    configLoaderClass: com.networknt.server.DefaultConfigLoader
    host: ${sidecar.startup.host:dev.lightapi.net}
    serviceId: ${sidecar.startup.serviceId:com.networknt.petstore-lpsc-3.1.0}
    envTag: ${sidecar.startup.envTag:dev}
    acceptHeader: application/yaml
    timeout: ${sidecar.startup.timeout:3000}
